// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecomerces.Data;

#nullable disable

namespace ecomerces.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230110143321_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ecomerces.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ecomerces.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://cdn.tgdd.vn/Products/Images/42/249720/TimerThumb/vivo-y15s-2021-(12).jpg",
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://fptshop.com.vn/Uploads/Originals/2021/9/4/637663485438013374_msi-modern-14-xam-dd.jpg",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://images.samsung.com/is/image/samsung/p6pim/vn/ef-bt730pbegww/gallery/vn-galaxy-tab-s7-fe-bt730-ef-bt730pbegww-thumb-499778061?$264_264_PNG$",
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/1/_/1_258.jpg",
                            Name = "Watch"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://antien.vn/uploaded/Bose%20Headphone%20700/tai-nghe-bluetooth-chong-on-bose-headphones-700.jpg",
                            Name = "Headphone"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://vn.jbl.com/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwd04e5f23/1_JBL_PARTYBOX_110_HERO_x2.jpg?sw=270&sh=330&sm=fit&sfrm=png",
                            Name = "Speaker"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://hanoicomputercdn.com/media/product/60800_camera_ip_wifi_quay_quet_thong_minh_ezviz_c6n_4mp_sp.png",
                            Name = "Camera"
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://phongnet.com/wp-content/uploads/2022/09/mainboard-asus-h510m-k-chinh-hang.jpg",
                            Name = "Main board"
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://cdn.techzones.vn/Data/Sites/1/News/3246/techzones-top-nhung-cpu-may-tinh-manh-nhat-hien-nay.jpg",
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://www.sieuthimaychu.vn/datafiles/setone/16027492188296.jpg",
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://m.media-amazon.com/images/I/81kf3+5l2LS._SL1500_.jpg",
                            Name = "VGA"
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://www.sieuthimaychu.vn/datafiles/setone/16240015291425.png",
                            Name = "SSD"
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://kccshop.vn/media/product/250-963-44444_hdd_seagate_barracuda_2tb.jpg",
                            Name = "HDD"
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://gland.vn/media/news/1501_vo-case-6.jpg",
                            Name = "Case"
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://npcshop.vn/media/product/250-3800-63449_rm850_____850_watt_80_plus_gold_fully__7_.jpg",
                            Name = "PSU"
                        },
                        new
                        {
                            Id = 16,
                            Image = "https://files.pccasegear.com/images/1625009304-ROG-STRIX-LC-II-360-ARGB-thb.jpg",
                            Name = "Cooler"
                        });
                });

            modelBuilder.Entity("ecomerces.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Iphone 12",
                            Image = "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/1/_/1_252.jpg",
                            Name = "Iphone 12",
                            Price = 14790000m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Iphone 12 Pro",
                            Image = "https://cdn.tgdd.vn/Products/Images/42/213032/iphone-12-pro-xam-new-600x600-2-600x600.jpg",
                            Name = "Iphone 12 Pro",
                            Price = 16790000m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Iphone 12 Pro Max",
                            Image = "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xam-new-600x600-200x200.jpg",
                            Name = "Iphone 12 Pro Max",
                            Price = 18790000m,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ecomerces.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "huyhieu.nguyenphan@gmail.com",
                            Name = "Huy Hieu",
                            Password = "Sp140802"
                        });
                });

            modelBuilder.Entity("ecomerces.Models.Product", b =>
                {
                    b.HasOne("ecomerces.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
